name: milijunas
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+103

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  package_info: ^2.0.2
  http: ^0.13.3
  sqflite: ^2.0.0+4
  shared_preferences: ^2.0.7
  url_launcher: ^6.0.10
  just_audio: ^0.9.17
  restart_app: ^1.1.0
  device_info: ^2.0.3
  intl: ^0.17.0
  google_mobile_ads: ^0.13.6


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/milijunas_logo.png
    - assets/black_box_menu.png
    - assets/black_box_answer.png
    - assets/yellow_box_answer.png
    - assets/green_box_answer.png
    - assets/red_x.png
    - assets/coin.png

    - assets/music/

    - assets/jokers/

  uses-material-design: true
